# Generated by Django 4.2.7 on 2023-11-15 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('book_name', models.CharField(max_length=200)),
                ('entry_timestamp', models.DateTimeField(default=datetime.datetime(2023, 11, 15, 6, 38, 33, 898416, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
