# Generated by Django 4.2.7 on 2023-11-16 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0002_alter_bookquote_entry_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entry_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('text_title', models.CharField(max_length=200)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essence.quote')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essence.quote')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=200)),
                ('title', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookQuote',
        ),
        migrations.AddField(
            model_name='youtubequote',
            name='youtube_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='essence.youtubevideo'),
        ),
    ]
