# Generated by Django 4.2.7 on 2023-11-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0003_quote_textquote_youtubequote_youtubevideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textquote',
            name='id',
        ),
        migrations.RemoveField(
            model_name='youtubequote',
            name='id',
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textquote',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='essence.quote'),
        ),
        migrations.AlterField(
            model_name='youtubequote',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='essence.quote'),
        ),
    ]
