# Generated by Django 4.2.7 on 2023-11-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0004_remove_textquote_id_remove_youtubequote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubequote',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textquote',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='essence.quote'),
        ),
        migrations.AlterField(
            model_name='youtubequote',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.quote'),
        ),
    ]
