# Generated by Django 4.2.7 on 2023-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0007_alter_youtubevideo_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='youtubequote',
            constraint=models.CheckConstraint(check=models.Q(('end_seconds__gt', models.F('start_seconds'))), name='check_end_seconds'),
        ),
    ]
