# Generated by Django 4.2.7 on 2023-11-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0008_youtubequote_check_end_seconds'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='youtubequote',
            constraint=models.CheckConstraint(check=models.Q(('start_seconds__gte', 0)), name='check_start_seconds'),
        ),
    ]
